# docker-compose.yml (for local development)
version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secret-key-change-this
      - PORKBUN_API_KEY=your-porkbun-api-key
      - PORKBUN_SECRET_KEY=your-porkbun-secret-key
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=your-openai-key
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=domaindb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: